### ISSUE TITLE
Check-in

### ISSUE THREAD

**Issue by tylernguyen** [acoutts/x1c7-hackintosh#2]
hey @acoutts 

Not sure if this may interest you, but https://github.com/suhrmann/x1c7-hackintosh have gotten the x1c7 to work quite well. If you're still in the market, I'm fairly sure the x1c8 will also likely to work with the newest OpenCore. In addition, the folks at https://github.com/OpenIntelWireless are working hard on Intel wireless support, so a wifi card replacement isn't really needed.

**Comment by acoutts** [comment]
Thanks for that!! I'll keep an eye on the wifi project 👍👍

**Comment by LEXUGE** [comment]
I got the same model 20R1, and I am able to get it to work with OpenCore 0.7.5.

However, I am interested in the status of the WWAN drive here. Is it completely unusable? Or can I use it as a storage drive?
